### ISSUE TITLE
Support NodaTime 2.0

### ISSUE THREAD

**Issue by mateuszlewko** [logary/logary#240] opened 2017-04-05 23:58 UTC
Updating NodaTime to 2.0 breaks logary. Works fine with older 1.x versions.
Here is exception I've got after updating NodaTime:

> Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$XXMyAppXX>.$Program' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Logary>.$Targets_Core' threw an exception. ---> System.MissingMethodException: Method not found: 'NodaTime.Duration NodaTime.Duration.FromHours(Int64)'.
   at <StartupCode$Logary>.$Targets_Core..cctor()
   --- End of inner exception stack trace ---
   at Logary.Targets.LiterateConsole.get_empty()

**Comment by haf** [comment] 2017-04-06 06:15
Duplicate of #239

**Closed by haf** 2017-04-06 06:15 UTC
