### ISSUE TITLE
Logging.getCurrentLogger null exception

### ISSUE THREAD

**Issue by Risord** [logary/logary#276] opened 2018-02-06 14:11 UTC
Hi

I am using logary with WebApi 2 (F#) and got runtime exception during logger initialization.

Usage:
```
type SomeController() =
    inherit BaseController()

    let logger = Logary.Logging.getCurrentLogger()

    [<HttpGet; Route("some/task")>]
    member x.GetSomeTask() =
        ...
```

Crash happen inside `src/Logary/Logging.fs: getCurrentLoggerName` because type passed to `getName` is null. Method got from `StackFrame` is lambda_method and it's DeclaringType is null. Successors are passed to frame_still_unrolling_or_is_in_dotnet_core function which seems to do null checking(?) but type null checking is never done to default m variable.

In another words this unexpected null got from here (41):
` |> Seq.append (Seq.singleton (m, `**m.DeclaringType**`)) // unless we...`

Replicating details are a bit shady because identical usage elsewhere has worked just fine.

**Comment by haf** [comment] 2018-02-06 17:54
This is a new problem with a new C# compiler. It's not a bug in the logic itself; although perhaps you can add a skip on null-check.

Also, for troublesome classes, you can use Logging.getLoggerByName "SomeController" to workaround the problem.

Leaving it open for a bit if you want to fix it, closing in 90 days w/ or w/o a fix.

**Closed** 2018-03-17 14:32 UTC
Labels: question
